import { useRef, useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { useAuthActions } from "@convex-dev/auth/react";
import { makeFunctionReference } from "convex/server";

const list = makeFunctionReference<"query">("posts:list");
const publish = makeFunctionReference<"mutation">("posts:publish");
const uploadUrl = makeFunctionReference<"mutation">("posts:generateUploadUrl");
const names = ["Jaco", "Franli", "Caleb", "Ryno", "Hayley", "Sanri"];
const slug = (name: string) => name.toLowerCase().replace(/\s+/g, "");
const date = new Intl.DateTimeFormat("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" });
type FileItem = { storageId: string; kind: "image" | "video"; preview: string };

export default function App() {
  const posts = (useQuery(list) ?? []) as any[];
  const doPublish = useMutation(publish);
  const getUploadUrl = useMutation(uploadUrl);
  const { signIn, signOut } = useAuthActions();
  const [author, setAuthor] = useState("Jaco"), [password, setPassword] = useState(""), [admin, setAdmin] = useState(false), [compose, setCompose] = useState(false), [title, setTitle] = useState(""), [body, setBody] = useState(""), [location, setLocation] = useState(""), [files, setFiles] = useState<FileItem[]>([]), [busy, setBusy] = useState(false), [notice, setNotice] = useState("");
  const picker = useRef<HTMLInputElement>(null);
  async function login() { setBusy(true); try { await signIn("password", {email:`${slug(author)}@america2026.trip`, password, flow:"signIn"}); setAdmin(false); setPassword(""); setCompose(true); } catch { setNotice("That password did not work."); } finally { setBusy(false); } }
  async function addMedia(source: FileList | null) { if (!source) return; setBusy(true); try { const added: FileItem[]=[]; for(const file of Array.from(source).slice(0,8-files.length)){ if(!(file.type.startsWith("image/")||file.type.startsWith("video/"))) continue; if(file.size>40*1024*1024) throw Error("Each photo or video must be 40 MB or smaller."); const url=await getUploadUrl(); const res=await fetch(url,{method:"POST",headers:{"Content-Type":file.type},body:file}); if(!res.ok) throw Error("An upload did not finish."); const {storageId}=await res.json(); added.push({storageId,kind:file.type.startsWith("video/")?"video":"image",preview:URL.createObjectURL(file)}); } setFiles(x=>[...x,...added]); } catch(e){setNotice(e instanceof Error?e.message:"Upload failed.");} finally {setBusy(false); if(picker.current)picker.current.value="";} }
  async function post(){ setBusy(true);try{await doPublish({title,body,location,media:files.map(({storageId,kind})=>({storageId,kind}))});files.forEach(x=>URL.revokeObjectURL(x.preview));setTitle("");setBody("");setLocation("");setFiles([]);setCompose(false);setNotice("Your dispatch is live.");}catch(e){setNotice(e instanceof Error?e.message:"Could not publish.");}finally{setBusy(false);} }
  return <><header><a className="brand" href="/"><span>AMERICAN</span> POSTCARDS</a><div className="route">JNB <b>✦</b> NYC <b>✦</b> SEA</div><button className="admin-link" onClick={()=>setAdmin(x=>!x)}>{admin?"Close":"Publisher sign in"}</button></header>
  {admin&&<section className="login"><label>Publish as<select value={author} onChange={e=>setAuthor(e.target.value)}>{names.map(n=><option key={n}>{n}</option>)}</select></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void login()}/></label><button onClick={()=>void login()} disabled={busy}>Sign in & write</button></section>}
  <main><section className="hero"><p>AMERICA · SUMMER 2026</p><h1>Stories from<br/><i>the open road.</i></h1><div className="flag"><span></span><span></span><span></span><span></span><span></span></div><p className="intro">A family journey in small, honest dispatches — the streets, the food, the people and the moments worth keeping.</p>{compose&&<button className="write" onClick={()=>setCompose(true)}>Write a dispatch <b>→</b></button>}</section>
  {compose&&<section className="editor"><div className="editor-title">NEW DISPATCH <button onClick={()=>setCompose(false)}>×</button></div><input className="headline" placeholder="Give this moment a title" value={title} onChange={e=>setTitle(e.target.value)} maxLength={100}/><input placeholder="Where are you?  e.g. Brooklyn, New York" value={location} onChange={e=>setLocation(e.target.value)} maxLength={80}/><textarea placeholder="Tell the story. A little more than a caption…" value={body} onChange={e=>setBody(e.target.value)} maxLength={2500}/><input hidden ref={picker} type="file" accept="image/*,video/*" multiple onChange={e=>void addMedia(e.target.files)}/>{files.length>0&&<div className="previews">{files.map((f,i)=><div key={f.preview}>{f.kind==="video"?<video src={f.preview}/>:<img src={f.preview}/>}<button onClick={()=>setFiles(xs=>xs.filter((_,n)=>n!==i))}>×</button></div>)}</div>}<div className="editor-actions"><button className="media" onClick={()=>picker.current?.click()} disabled={busy}>{busy?"Working…":"Add photos / video"}</button><button className="publish" disabled={busy||!title.trim()||!body.trim()} onClick={()=>void post()}>Publish →</button></div></section>}
  <section className="feed">{posts.length===0?<div className="empty"><span>THE FIRST MILE</span><h2>We’re on our way.</h2><p>The first proper postcard will arrive soon.</p></div>:posts.map(post=><article key={post._id}><div className="meta"><span>{post.location||"ON THE ROAD"}</span><time>{date.format(new Date(post.publishedAt))}</time></div><h2>{post.title}</h2><p>{post.body}</p>{post.media?.length>0&&<div className={`gallery n${Math.min(post.media.length,4)}`}>{post.media.map((m:any,i:number)=>m.kind==="video"?<video key={m.storageId} src={m.url||undefined} controls playsInline/>:<img key={m.storageId} src={m.url||undefined} alt={`${post.title} ${i+1}`}/>)}</div>}<footer>POSTED BY {post.author.toUpperCase()} <b>★</b></footer></article>)}</section></main>{notice&&<div className="toast" onClick={()=>setNotice("")}>{notice}</div>}<footer className="site-footer">AMERICAN POSTCARDS · 2026</footer></>;
}
